### ISSUE TITLE
Ocean Floor Terrain Doesn't Look Right...

### ISSUE THREAD

**Issue by miclol** [almic/VanillaTrees#5]
What I Expected:
![image](https://user-images.githubusercontent.com/64191125/131228142-e37fe0fa-aa4d-4c0f-a730-18df1ca00b6f.png)

What I Got:
![image](https://user-images.githubusercontent.com/64191125/131228115-540347bf-4538-4de1-a34b-9699f95c8731.png)

**Comment by miclol** [comment]
Apparently, you can bypass this by just using the material as a terrain directly, but I guess you can still look into this?

**Comment by DerMattinger** [comment]
Looks like there is too much dirt. The rest is "kind of grouped" like it should be. Just dirt covering parts of it.
Can you check if the layer is really covering 100% of the area. You can also select an intensity when painting layers.
Or send the worldpainter *.world file with your map (or just the small section with the error)

**Comment by miclol** [comment]
I used Global Operation to fill the ocean with layer "Lukewarm Ocean". Here's the .world folder in a .zip folder
[OceanTest.zip](https://github.com/almic/VanillaTrees/files/7085224/OceanTest.zip)

**Comment by miclol** [comment]
Turns Out I have the big dumb. I didn't slide the fill slider all the way to the right to make it Intensity 100%. Closing Issue.

**Comment by almic** [comment]
Glad you got this figured out, sorry I am bad at checking my notifications!
